# Generated by Django 6.1.1 on 2026-10-05 07:39

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short introduction shown on the homepage.'),
        ),
    ]
