# Generated by Django 6.1.1 on 2026-10-05 07:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_homepage_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='tagline',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short tagline shown below the main title.'),
        ),
    ]
