# Generated by Django 6.1.1 on 2026-10-05 08:02

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_homepage_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about',
            field=wagtail.fields.RichTextField(blank=True, help_text='About section shown on the homepage.'),
        ),
    ]
