# Generated by Django 6.1.1 on 2026-10-05 08:15

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_homepage_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact',
            field=wagtail.fields.RichTextField(blank=True, help_text='Contact information.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='experience',
            field=wagtail.fields.RichTextField(blank=True, help_text='Professional experience.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='projects',
            field=wagtail.fields.RichTextField(blank=True, help_text='Main projects and portfolio.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='skills',
            field=wagtail.fields.RichTextField(blank=True, help_text='Skills and technologies.'),
        ),
    ]
