# Generated by Django 6.1.1 on 2026-10-05 08:28

import django.db.models.deletion
import wagtail.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0099_redirect'),
        ('website', '0005_homepage_contact_homepage_experience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.WAGTAIL_PAGE_MODEL)),
                ('short_description', wagtail.fields.RichTextField(blank=True, help_text='Short project description.')),
                ('technologies', wagtail.fields.RichTextField(blank=True, help_text='Technologies used in this project.')),
                ('project_url', models.URLField(blank=True, help_text='Live project URL.')),
                ('github_url', models.URLField(blank=True, help_text='GitHub repository URL.')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='homepage',
            options={},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='projects',
            field=wagtail.fields.RichTextField(blank=True, help_text='Short introduction for the projects section.'),
        ),
    ]
