# Generated by Django 6.1.1 on 2026-10-05 08:43

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_projectpage_alter_homepage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectpage',
            options={},
        ),
        migrations.AddField(
            model_name='projectpage',
            name='description',
            field=wagtail.fields.RichTextField(blank=True, help_text='Detailed project description.'),
        ),
    ]
