# Generated by Django 6.1.1 on 2026-10-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_projectpage_options_projectpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='cv_url',
            field=models.URLField(blank=True, help_text='CV or resume URL.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='github_url',
            field=models.URLField(blank=True, help_text='GitHub profile URL.'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL.'),
        ),
    ]
