# Generated by Django 6.1.1 on 2026-10-05 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0027_image_description'),
        ('website', '0008_homepage_cv_url_homepage_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='profile_image',
            field=models.ForeignKey(blank=True, help_text='Profile image shown on the homepage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Project cover image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
