# Generated by Django 6.1.1 on 2026-10-06 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_homepage_profile_image_projectpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpage',
            name='project_type',
            field=models.CharField(blank=True, help_text='Type of project, for example Personal Project or Client Project.', max_length=100),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='role',
            field=models.CharField(blank=True, help_text='Your role in this project.', max_length=100),
        ),
        migrations.AddField(
            model_name='projectpage',
            name='status',
            field=models.CharField(blank=True, help_text='Current project status.', max_length=100),
        ),
    ]
