# Generated by Django 6.1.1 on 2026-10-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_projectpage_project_type_projectpage_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='projectpage',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='website.projecttag'),
        ),
    ]
