# Generated by Django 6.1.1 on 2026-10-07 18:11

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('website', '0011_projecttag_projectpage_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectpage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='ProjectTag',
        ),
        migrations.AddField(
            model_name='projectpage',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='Add tags such as Django, Python, AI, REST API.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
